Feature/app v1
gersonhiggins/budget-app pull request #1
Opened 2023-10-19 19:33 UTC by gersonhiggins

The user should be able to register in the app with full name, email and password (all mandatory).
The user can log into the app using email and password.
If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
Home page (categories page)

When the user logs in, they are presented with the categories page.
For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
Transactions page

For a given category, the list of transactions is presented, ordered by the most recent.
At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
When the user clicks on the "Back" button (<), the user navigates to the home page.
"Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).
The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.
"Add a new transaction" page

The user fills out a form to create a new transaction with:
name (mandatory)
amount (mandatory)
categories (mandatory at least one)
The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

2023-10-19 21:09 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @gersonhiggins 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors 🟢 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please record a demo video highlighting the features of your project 🙏 
![image](https://github.com/gersonhiggins/budget-app/assets/46839548/584770a5-c514-4adb-8064-b689eb4c6e84)
- [ ] Please give appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).
- [ ] Please ensure that the project is deployed as stated in the project requirements 👍 
- [ ] Please implement a splash screen when a user visits the root of your application just as stated in the requirements below 👇 
![image](https://github.com/gersonhiggins/budget-app/assets/46839548/852f976c-0655-48f6-86d7-6b85c7bb01f8)
- [ ] Please write unit and integration tests for all the most important components of the application.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-19 21:09 UTC, codepantha commented on app/controllers/entities_controller.rb
> +  end
- [ ] An error occurs while attempting to create a transaction. Please fix the bug as shown below 👇 
![image](https://github.com/gersonhiggins/budget-app/assets/46839548/fb5d004d-faab-4329-9823-d0c04b801cfc)

2023-10-19 21:15 UTC, gersonhiggins commented
hello @codepantha, i got this eeror trying to deploy the server, "
Oct 19 03:07:48 PM  rake aborted!
Oct 19 03:07:48 PM  ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
"

do you know how to fix it, please

2023-10-19 21:22 UTC, gersonhiggins commented on app/controllers/entities_controller.rb
> +  end
i dont hace that on my pc are you sure?

2023-10-19 21:22 UTC, gersonhiggins commented on app/controllers/entities_controller.rb
> +  end
![image](https://github.com/gersonhiggins/budget-app/assets/128397949/e5e72a39-c0ac-470e-9c22-35abf464ef16)

2023-10-19 21:22 UTC, gersonhiggins commented on app/controllers/entities_controller.rb
> +  end
@codepantha

2023-10-20 19:11 UTC, cynthiainga requested changes
Hi @gersonhiggins, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

 ## Highlights

- [ ] Correct Gitflow ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Has a deployed link ✔️ 

 ## Required Changes ♻️

- [ ] As mentioned by the previous reviewer you should record a video that meets all the requirements, the video should contain a highlight about a piece of the code that you find interesting or are proud of making. Also kindly explain correctly how your application works 😁 🙃 
- [ ] As mentioned by the previous reviewer and in the requirements kindly write unit and integration tests for all the most important components of the application.
- [ ] Kindly check the comment under the review 👇🏾 👇🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 19:11 UTC, cynthiainga commented on app/views/users/index.html.erb
- [ ] Good job by adding the splash screen, but you should make sure to follow the given design 🙃 

Your design

<img width="375" alt="Screenshot 2023-10-20 at 22 02 41" src="https://github.com/gersonhiggins/budget-app/assets/74501523/f626f42e-d788-4fdc-96a0-2551b2696cc3">

Given design

<img width="384" alt="Screenshot 2023-10-20 at 22 04 15" src="https://github.com/gersonhiggins/budget-app/assets/74501523/446b2c9b-9c4f-4397-8cd3-13727e8c3f4d">

2023-10-20 21:48 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @gersonhiggins, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights :green_circle: 

- Nice job for properly validating all user's input :+1: 




Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-10-20 21:48 UTC, FrederickMih commented on config/routes.rb
> +  end
- [Optional] Based on the requirements, we were supposed to only add necessary routes corresponding  to the controller actions we implemented. By using resourceful routing, 7 routes are generated by default while you didn't implement all the actions.

2025-05-11 02:48 UTC, merged